# docker-compose.yml - Full Stack Application
networks:
  transcription-network:
    driver: bridge

services:
  # Backend FastAPI
  backend:
    build: 
      context: ./api
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: transcription-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - transcription-network
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - VERSION_MODEL=${VERSION_MODEL:-large-v3}
      - FORCE_CPU=${FORCE_CPU:-true}
      - AUDIOS_DIR=/app/public/audios
      - TRANSCRIPTIONS_DIR=/app/public/transcriptions
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=/app/logs/app.log
      - PYTHONUNBUFFERED=1
      - HF_HOME=/app/cache/huggingface
      - MPLCONFIGDIR=/home/appuser/.config/matplotlib
      - HOME=/home/appuser
      - XDG_CACHE_HOME=/home/appuser/.cache
      - XDG_CONFIG_HOME=/home/appuser/.config
      - CTRANSLATE2_SUPPRESS_WARNING=1
      - OMP_NUM_THREADS=1
    volumes:
      # Volumes de dados persistentes
      - type: bind
        source: ./api/public/audios
        target: /app/public/audios
        bind:
          create_host_path: true
      - type: bind
        source: ./api/public/transcriptions
        target: /app/public/transcriptions
        bind:
          create_host_path: true
      - type: bind
        source: ./api/public/videos
        target: /app/public/videos
        bind:
          create_host_path: true
      - type: bind
        source: ./logs
        target: /app/logs
        bind:
          create_host_path: true
      # Cache volumes (bind mounts to preserve permissions)
      - type: bind
        source: ./cache/huggingface
        target: /app/cache/huggingface
        bind:
          create_host_path: true
      - type: bind
        source: ./cache/torch
        target: /app/cache/torch
        bind:
          create_host_path: true
      - type: volume
        source: matplotlib_config
        target: /home/appuser/.config/matplotlib
        volume:
          nocopy: true
      # Volumes de desenvolvimento (comentar em produção)
      - ./api/src:/app/src
      - ./api/main.py:/app/main.py
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    security_opt:
      - no-new-privileges:true
    init: true

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transcription-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - transcription-network
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    init: true
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

volumes:
  matplotlib_config:
    name: transcription_matplotlib_config